name: Docker build and push vonage messaging
on:
  push:
    branches:
      - main
    paths:
      - providers/vonage-messaging/**

env:
  TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  IMAGE_NAME: "kinluek/vonage-messaging"
  IMAGE_TAG: "1.0.4"
  ARGOCD_IMAGE_FILE_URL: "https://api.github.com/repos/sichan-vonage/argo-cd-demo-configs/contents/app-configurations/providers/vonage-messaging/values-dev-image.yaml"
  ARGOCD_REPO_URL: "https://api.github.com/repos/sichan-vonage/argo-cd-demo-configs"
  ARGOCD_REPO_FILE_PATH: "app-configurations/providers/vonage-messaging/values-dev-image.yaml"
  APP_NAME: "vonage-messaging"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        run: |
          docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}

      - name: docker build app dev
        run: |
          cd providers/vonage-messaging && docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .

      - name: docker push dev
        run: |
          docker push ${IMAGE_NAME}:${IMAGE_TAG}

  deploy:
    needs:
      - build
    runs-on: ubuntu-latest
    container:
      image: kinluek/automerger:1.0.3
    steps:
      - name: update config repo
        run: |
          app -github-user=sichan-vonage -github-token=${TOKEN_GITHUB} \
          -message="updating ${APP_NAME} image to tag ${IMAGE_TAG}" \
          -content="image_tag: ${IMAGE_TAG}" \
          -repo-url=${ARGOCD_REPO_URL} \
          -file-path=${ARGOCD_REPO_FILE_PATH}
