name: Docker build and push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: docker build app dev
        run: |
          cd app && docker build -t kinluek/app-dev:1.0.4 .

      - name: docker push dev
        run: |
          docker push kinluek/app-dev:1.0.4

      - name: docker build app prod
        run: |
          cd app && docker build -t kinluek/app-prod:1.0.3 .

      - name: docker push prod
        run: |
          docker push kinluek/app-prod:1.0.3